name: build
on:
  - push
jobs:
  build_image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - name: "Build Image"
        run: docker image build --tag=project_jee:latest ./