name: build
on:
  - push
jobs:
  check-dockerfile:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
  build_image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - name: "Build Image"
        run: docker image build --tag=project_jee:latest ./
      - name: "start image"
        run: docker run project_jee:latest bash echo 'test'
